### ISSUE TITLE
view_power: exiting the program throws an exception  (ros ticket #3606)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_power_drivers#29]
Choosing File / Exit spews multiple exceptions, e.g.

{{{
[ERROR] 1263681190.359594: bad callback: <bound method PowerBoardPanel.diagnostics_callback of wxPython wrapper for DELETED PowerBoardPanel object! (The C++ object no longer exists.)>
Traceback (most recent call last):
  File "/u/tfield/latest/ros/core/rospy/src/rospy/topics.py", line 547, in _invoke_callback
    cb(msg)
  File "/u/tfield/latest/work/pr2_power_board/src/pr2_power_board/pr2_power_board_panel.py", line 149, in diagnostics_callback
    self._mutex.acquire()
  File "/usr/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14314, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the PowerBoardPanel object has been deleted, attribute access no longer allowed.

Unhandled exception in thread started by 
Error in sys.excepthook:

Original exception was:
}}}

trac data:
- Owner: **tfield**
- Reporter: **tfield**
- Reported at: **Sat Jan 16 14:37:40 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/3606

**Comment by ahendrix** [comment]
[tfield] r29307

fixed
