### ISSUE TITLE
lexical_cast exception causing power_monitor crash on PRL  (ros ticket #4566)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_power_drivers#52]
I'm trying to start PRL with cturtle, and I'm getting the following error: [[BR]]
'''`terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boos
t::bad_lexical_cast> >'`'''

Backtrace:
{{{
#0  0x00007f2763b80fb5 in raise () from /lib/libc.so.6
#1  0x00007f2763b82bc3 in abort () from /lib/libc.so.6
#2  0x00007f27646420b4 in __gnu_cxx::__verbose_terminate_handler () from /usr/lib/libstdc++.so.6
#3  0x00007f27646404b6 in ?? () from /usr/lib/libstdc++.so.6
#4  0x00007f27646404e3 in std::terminate () from /usr/lib/libstdc++.so.6
#5  0x00007f27646405ca in __cxa_throw () from /usr/lib/libstdc++.so.6
#6  0x000000000043d519 in boost::detail::lexical_cast<unsigned int, std::string, false, char> (arg=<value optimized out>,

```
buf=0x7fff9e2b7380 "�s+\236�\177", src_len=<value optimized out>) at /usr/include/boost/throw_exception.hpp:64
```
#7  0x000000000043bb4c in power_monitor::AdvancedPowerStateEstimator::readObservations (this=0x7f2754004fa0, log=@0x7f2754004fd0)

```
at /usr/include/boost/lexical_cast.hpp:1166
```
#8  0x000000000043c36c in AdvancedPowerStateEstimator (this=0x7f2754004fa0)

```
at /opt/ros/cturtle/stacks/pr2_power_drivers/power_monitor/src/power_state_estimator.cpp:88
```
#9  0x000000000041db28 in PowerMonitor (this=0x7fff9e2b7cc0) at /opt/ros/cturtle/stacks/pr2_power_drivers/power_monitor/src/power_mon

itor.cpp:58
#10 0x000000000041e931 in main (argc=1, argv=0x7fff9e2b8028) at /opt/ros/cturtle/stacks/pr2_power_drivers/power_monitor/src/power_mon

itor.cpp:243
}}}

Looks like lexical cast is failing in '''`AdvancedPowerStateEstimator::readObservations`'''.

trac data:
- Owner: **tfield**
- Reporter: **vpradeep**
- Reported at: **Mon Jul 19 10:05:34 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4566

**Comment by ahendrix** [comment]
[tfield] #4470
